const terminalOutput = document.getElementById('output');
const globeArt = `
                      ...........                                                                   
                    ...',,;::::c:::;,'..                                                            
                    ....',,;::cclloodddol:,..                                                       
....                 ....'',;::clloodddxxkkxdc,.                                                    
.....                 ....'',;::clloddxxkkOO000kl,..                                                
'..                    ....'',;::clloddxxkOO00KKK0Ox:.                                              
.                       ....',,;::clloddxxkOO00KKKKXKkc.                                            
                        .....',;;:ccloodxxkkOO00KKXXXNXk:.                                          
                         ....'',;;:clloddxxkOO00KKXXXNNNKd'                                         
                         .....'',;;:ccloddxxkOO0KKKXXXNNNXk;.                                       
                          .....',,;::clloddxxkOO00KKKXXXNNN0:.                                      
                          .....'',;;:ccloodxxkOO00KKKXXNNWWW0c.                                     
                           .....',,;::clloddxkkO000KKXXNNNWWN0c.....                                
                            .....',,;::clloddxkkOO00KKXXNNNWWNk;........                            
                            .....'',;;:ccloodxxkOOO00KKXXNNWWWXd;,''.........                       
                             .....',,;::clloddxkkOOO0KKXXNNNNNNk:,;;,,''.........                   
                             .....'',;;:ccloodxxkkOO00KKXXNNNNNO;..',,;;,,'.........                
                              .....',,;::clloodxxkkOO00KKXXNNNNO; ....',,,;;,''.........            
                              .....'',;;:ccloodxxkkkO00KKXXNNNW0,    ....'',,;;,,'.........         
                               .....',;;:ccloodxxkkOO00KXXNNWWWO'       ....'',,;;,,'.........      
....                            ....'',;::cloodxkkOO00KKXNNWWWNd.          ....',,;;;,'..........   
,,''.....                        ....',;;:cllodxxkkO00KXXNNWWWK:             ....',,;;;,,'......... 
'',,,,,''......                  .....',;::cloodxkkkO0KKXXNNNXo.               ...'',,;;;,,'........
.....'',,,,,,''.......            ....'',;:ccloddxkkOO0KKXXNXx'                 ...'',,,;;,,,.......
...........'',,,,,,'''.......     .....',,;:cloodxxkkO0KKXXXx'                 .....',,,;;;,,,......
    .............''',,,,,,,'''..........'',;::clooddxxkOOOkl.                 .....',,,,;;;,,,,. ...
          .............'''',,,,,,,,,'''''',,,;;::ccclllooc,.           .........''',,,,;;;;,,,,. ...
                ...............'''',,,,,,,,,,,,,,,,,;;;;;,...............''''',,,,;;;;;;;;,,,'......
                       ...............''',,,,,;;,;;;;;;;,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;,,'.........
                               ..........''''''''''''''''''',,,,,,,,;;;;;;;;;;,,,,,'''..............
                                      ..............................................................
                                                  ..................................................
                                                                  ..........................        
`;
const texts = globeArt.split('\n');
let currentText = 0;
let currentChar = 0;

function typeOutText() {
    if (currentText < texts.length) {
        let text = texts[currentText];
        if (currentChar < text.length) {
            terminalOutput.innerHTML += text.charAt(currentChar);
            currentChar++;
            setTimeout(typeOutText, 1); // Increased typing speed
        } else {
            terminalOutput.innerHTML += '<br>';
            currentText++;
            currentChar = 0;
            setTimeout(typeOutText, 1); // Shorter delay before next line
        }
    } else if (currentText === texts.length) {
        // Correctly append only once at the end of the globe art typing
        terminalOutput.innerHTML += '<span id="nexus">Nexus Explorer</span><br><span id="blinker">Press any key to proceed</span>';
        currentText++; // Increment to prevent this block from running again
    }
}

document.addEventListener('keydown', () => {
    window.location.href = 'map.html';
});

window.onload = typeOutText;
