logging:
  level: info

database:
  pool_size: 20

layers:
  my_layer:
    table_name: my_table
    geometry_column: geom
    id_column: id
    srid: 4326
    properties:
      - name
      - description