version: '3.8'

services:
  postgis:
    build:
      context: .
      dockerfile: dockerfile.postgis
      healthcheck:
       test: ["CMD-SHELL", "pg_isready -U youruser -d yourdatabase -h localhost"]
       interval: 10s
       timeout: 5s
       retries: 5
    container_name: postgis_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  martin:
    image: ghcr.io/maplibre/martin:latest
    container_name: martin_dev
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
    entrypoint: ["/wait-for-it.sh", "postgis:5432", "--"]
    command: ["martin", "--config", "/config/config.yaml"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      
volumes:
  postgis_data: