version: '3.8'

services:
  postgis:
    build:
      context: .
      dockerfile: dockerfile.postgis
    container_name: postgis_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  martin:
    image: ghcr.io/maplibre/martin:latest
    container_name: martin_dev
    depends_on:
      - postgis
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "postgis:5432", "--", "martin", "--config", "/config/config.yaml"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      
volumes:
  postgis_data: