# Dockerfile.postgis
FROM postgis/postgis:latest

# Copy the initialization script into the container
COPY init-db.sh /docker-entrypoint-initdb.d/init-db.sh

# Make sure the script is executable
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh
